### ISSUE TITLE
Постраничная навигация блогов налезла на футер сайта

### ISSUE THREAD

**Issue by kononovandre** [CheDESIGNER/prestige#19]
Когда много блогов и они поделены на две страницы, то вот такое происходит
http://clip2net.com/s/5HoyRu

**Comment by 5nook** [comment]
вкурсе об этой проблеме :) поправим

**Comment by 5nook** [comment]
@Chedesigner пожалуйста создай много блогов с красивыми картинками и названиями чтобы я мог поправить этот момент на демке :) спасибо!

**Comment by CheDESIGNER** [comment]
Хорошо, создам завтра :)
