### ISSUE TITLE
Летит верстка в опере

### ISSUE THREAD

**Issue by kononovandre** [CheDESIGNER/prestige#20]
Версия оперу последняя. 
Вот что происходит
http://clip2net.com/s/5HomBy

**Comment by 5nook** [comment]
ох уж эта последняя опера, что ей спокойно не живется поправим

**Comment by 5nook** [comment]
неповерити это баг Оперы, об нем пишет весь Интернет
http://stackoverflow.com/questions/5443974/opera-outline-rendering-bug

но мы обошли его
