### ISSUE TITLE
Баг в комментах

### ISSUE THREAD

**Issue by CheDESIGNER** [CheDESIGNER/prestige#23]
http://livestreet.ru/uploads/images/01/72/96/2013/09/08/a24587.png
Наверное нужно добавить минимальную ширину, что бы меньше не становилось.

**Comment by 5nook** [comment]
можно, но это обычно настраивается в настройках LS эта лесенка.

покажи мне на простом сайте сколько лесенка максимум должна быть

**Comment by 5nook** [comment]
кстати ты поставл метку телефон, это на телефоне так??? у нас на телефоне другие комменты вообще, то что ты показал на картинке это либо планшет либо комп.

так где такое?

**Comment by CheDESIGNER** [comment]
Телефон в перевернутом режиме или "landscape". Посмотри топик с фотосетгм. С телефона не могу ссылку кинуть.

**Comment by 5nook** [comment]
ну допустим, я понял тебя :) 

так максимальную лесенку какую делать?

**Comment by CheDESIGNER** [comment]
Вот тема http://prestige.lstemplates.com/blog/gadgets/2.html

Ну что бы нормально отображались на мобиле в режиме "landscape"
