### ISSUE TITLE
Dropdown меню "Теги" и "Все блоги" не работают на некоторых страницах

### ISSUE THREAD

**Issue by CheDESIGNER** [CheDESIGNER/prestige#25]
https://catalog.livestreetcms.com/addon/trac/361/view/1349/#comment1

Заходим на сайт -> Щёлкаем 'теги' в меню сайта -> выбираем любой тег и переходим по нему -> отображаются топики с тегом, который мы выбрали -> Баг: нажимаем снова в меню на 'теги', но увы ничего не происходит, тоже самое при нажатии на кнопку 'все блоги'.

**Comment by 5nook** [comment]
скорей всего плохо настроен вывод блоков.

учтем в написании вики и инструкции

**Comment by 5nook** [comment]
в алто это и так поправлено
