### ISSUE TITLE
Ошибка niceurl + плагин

### ISSUE THREAD

**Issue by Killallpeople** [CheDESIGNER/prestige#26]
При включении плагина niceurl и Реклама пользователей появляется ошибка при создании топиков и блогов:

Warning: Invalid argument supplied for foreach() in plugins/niceurl/classes/modules/topic/Topic.class.php  on line 32

Тоже самое появляется при включении еще одного плагина.

**Comment by Killallpeople** [comment]
Ошибка появлялась на тестовом поддомене, при установке на сайт повторить не удалось. Плагины те же, хз в чем была причина.

**Comment by 5nook** [comment]
сомневаюсь что эта ошибка шаблона, тут же явно ошибка плагина.

У шаблона нет таких возможностей чтобы сломать класс ) эта просто верстка, пока закрою таск так как не понятно вообще откуда ноги, если появится более точные объяснения, то откроем заново.

у меня не удалось выявить эту ошибку
