### ISSUE TITLE
Совместимость с галереей

### ISSUE THREAD

**Issue by Killallpeople** [CheDESIGNER/prestige#27]
В плагине галерея при активации все работает но нету кнопки "создать" альбом. + если зайти в профиль - публикации и включить альбом, едет верстка https://pp.vk.me/c409331/v409331906/4a1e/AEh6OnJim50.jpg

**Comment by CheDESIGNER** [comment]
Лучше подождите пока мы адаптируем этот плагин, сейчас он выглядит криво.
