### ISSUE TITLE
Не работает восстановление пароля

### ISSUE THREAD

**Issue by Killallpeople** [CheDESIGNER/prestige#29]
Очень часто кнопка восстановления пароля становится неактивной и не реагирует на нажатия, если нажать "ентер" то имейл с паролем отправляется. На вашем демо удалось повторить.
- https://github.com/Chedesigner/prestige/issues/25 очень раздражает, лучше исправить в первую очередь.

**Comment by 5nook** [comment]
не удалось повторить, сообщите какая ОС, какой браузер, какой разрешение монитора, спасибо.

**Comment by 5nook** [comment]
Так как не было долго ответа, закрываю
