### ISSUE TITLE
Адаптивный дизайн на ipad2 выходит за рамки

### ISSUE THREAD

**Issue by makhoov** [CheDESIGNER/prestige#30]
Правая часть сайта выезжает за поля
Пример:
http://quirktools.com/screenfly/#u=http%3A//testexperien.1gb.ru/&w=1024&h=600&a=1

**Comment by ekoum** [comment]
Такое же дело на iPad2.

**Comment by SimWhite** [comment]
На iPad3 (ретина) ситуация аналогична.

**Comment by 5nook** [comment]
это не баг, перевернутый ipad имеретин полноценную ширину аналогичного монитора на PC на 1024px

поэтому тут не чего нельзя сделать, закрываю
