### ISSUE TITLE
Сайт не отзывается на изменения в css

### ISSUE THREAD

**Issue by ekoum** [CheDESIGNER/prestige#33]
Вношу изменения в css файлы, загружаю на сервер, а все как было, так и остается. Например, решил убрать chelogo в футере, сделал в css файле линк на другие изображения — эффекта ноль, как был ваш лого, так и остался. В header меняю логотип, меняю размер через mod.css, заливаю, размер рамки остается какой и был.

**Comment by CheDESIGNER** [comment]
:)) Кэш отключили?
Если нет, то добавьте:

$config['sys']['cache']['use']    = false;
$config['compress']['css']['merge'] = false;
$config['compress']['js']['merge']  = false;

в файл config.local.php, над:

return $config;
?>

**Comment by ekoum** [comment]
Благодарю, товарищ :)
