### ISSUE TITLE
Отсутствует форматирование текста при просмотре топика из ленты.

### ISSUE THREAD

**Issue by Bennington** [CheDESIGNER/prestige#34]
Когда заходим в топик все впорядке

**Comment by CheDESIGNER** [comment]
Скрин можно?

**Comment by Bennington** [comment]
http://piccy.info/view3/5181822/4d04650eb7cee550993d101d30d0c35b/ лента

http://piccy.info/view3/5181828/a92188d3f902ab4c2b6057658b5935c3/ топик

**Comment by Bennington** [comment]
Критичная для меня недоработка

**Comment by CheDESIGNER** [comment]
Сегодня займемся

**Comment by Bennington** [comment]
иии?

**Comment by CheDESIGNER** [comment]
Терпение, делаем)

**Comment by 5nook** [comment]
Добавлена настройка в конфиг шаблона, вот такая:
$config['view']['text']['cuttag'] = 'off';

чтобы теги работали в ленте нужно поменять off на on
