### ISSUE TITLE
Баг пагинациии на странице поиска

### ISSUE THREAD

**Issue by CheDESIGNER** [CheDESIGNER/prestige#35]
http://flowi.ru/tag/%D0%92%D0%B8%D0%B4%D0%B5%D0%BE%D0%BA%D0%BB%D0%B8%D0%BF/

Переключателя страниц почти не видно, он заехал за футер.

**Comment by 5nook** [comment]
данный баг исправлен в последнем обновлении может либо дождаться оф релиза либо скачать с репозитория
