### ISSUE TITLE
Не работают кнопки "Следующий топик", "Предыдущий топик"

### ISSUE THREAD

**Issue by ermolaevpro** [CheDESIGNER/prestige#36]
В демо-версии повторил... В режиме "Больших превью" не работают кнопки "Следующий топик", "Предыдущий топик" в плавающем блоке слева...

Переходит непонятно куда, а не на следующий топик.

**Comment by ermolaevpro** [comment]
Тут вообще закрываются вопросы?

**Comment by CheDESIGNER** [comment]
https://github.com/Chedesigner/prestige/issues?page=1&state=closed

**Comment by 5nook** [comment]
К сожалению не так давно изменилась архитектура ls где все js основные, а так же отвечающие за этот переход, перенесли из шаблона в корень cms и шаблоном этот баг не исправить...

решил просто отключить отображение этих стрелок в режиме масонри и больших привью

возможно решение есть в написание отдельного плагина под это дело
