### ISSUE TITLE
Как убрать кнопки входа через соц. сети на странице авторизации?

### ISSUE THREAD

**Issue by ekoum** [CheDESIGNER/prestige#37]
Необходимо убрать кнопки входа через соц. сети на странице авторизации. Где искать код?

**Comment by CheDESIGNER** [comment]
templates\skin\prestige\actions\ActionLogin.tpl  28-32 строки

**Comment by ekoum** [comment]
Там есть только папка ActionLogin, в ней есть файл index.tpl. В нем есть эти строчки, но после их удаления кнопки не пропадают. Кэш отключен.

**Comment by 5nook** [comment]
да чего вы тут намудрили :)

человек наверное имел ввиду попап окошко, templates/skin/prestige/window_login.tpl
строки 30-34
