### ISSUE TITLE
Не отображаются все картинки в блоке "Новости в картинках"

### ISSUE THREAD

**Issue by vvlasenko** [CheDESIGNER/prestige#40]
Доброго времени суток. Почему то не отображает все картинки в блоке. Хотя превью имеется у всех постов. 

Линк - http://healthypeople.li/

**Comment by ermolaevpro** [comment]
Была такая же фигня.. Лечится из админки...
Раздел "Дополнительно".. Пункт меню "Провести переконвертацию всех превью к новым размерам из конфига
"..
У меня все заработало..
Надеюсь, что помог!

**Comment by vvlasenko** [comment]
Сделал что вы посоветовали @ermolaevpro и теперь исчезли вообще все картинки! Беда... Как пофиксить?

**Comment by ermolaevpro** [comment]
Ужас какой.. У меня все заработало.. странно.. Попробуйте из админки.. Плагины - Main preview topic - настройки

**Comment by CheDESIGNER** [comment]
Дайте мне доступ к админке сайта и к ФТП. Я посмотрю в чем причина.

**Comment by ermolaevpro** [comment]
@vvlasenko проблема решилась? Что было?

**Comment by 5nook** [comment]
вопрос решается настройкой конфига плагина майинпривью, который отвечает за эти привью, настраивается как указано в инструкции, после чего включает переконвертация или конвертация картинок для привью
