### ISSUE TITLE
Доработки на Альто

### ISSUE THREAD

**Issue by acobat** [CheDESIGNER/prestige#41]
Привет!
Мои пять копеек на неточности шаблона. Вроде - прошел по предыдущим авторам и ничего такого не нашел.

Работаем с Альто.
В Альто другая структура шаблонизации и тот пункт настройки с "блоками" попросту отсутвует в конфигах Альто. К тому-же - Альто не берет настроек с конфиг.пхп а все делаеться через админку. 
1. При большых превью - весь текст топика пишется сразу же под большой картинкой (как будто мы внутри топика уже). 
2. Не работает в дроп-меню кнопка "теги" - "все блоги". 

Пожалуйста - поставьте Альто и посмотрите чтоб все было нормально сверстано. А то очень криво - а шаблон потрясный. :)

Спасибо!

**Comment by 5nook** [comment]
"В Альто другая структура шаблонизации и тот пункт настройки с "блоками" попросту отсутвует в конфигах Альто. К тому-же - Альто не берет настроек с конфиг.пхп а все делаеться через админку."

Вкурсе, и не обязательно через админку все работает, а через виджет.php все так и настраивается. Пункт вы имели ввиду в инструкциях? Да еще не написали такую под алто. Скоро будет

"При большых превью - весь текст топика пишется сразу же под большой картинкой (как будто мы внутри топика уже)."

не понятно дайте принтскрин или линк

"Не работает в дроп-меню кнопка "теги" - "все блоги"."

Это беда все в тех же блоках они просто не настроены

"Пожалуйста - поставьте Альто и посмотрите чтоб все было нормально сверстано."

А вы думали мы этого не делали? http://prestigealto.lstemplates.com/ вот демка на алто, все сверстано как надо, где "криво", точней пжл чтобы мы вашу звезду в небе не искали :)

**Comment by acobat** [comment]
Не могли бы Вы, пожалуйста, в виде исключения, послать мне инструкцию настройки блоков на Альто? Я понял что это в Виджетах а только где и как? :)

На демке у вас там масорни а поставте ка BigPreview и оно все ползет :)

**Comment by acobat** [comment]
По поводу обреза вот скрин
http://s017.radikal.ru/i423/1309/60/737466272c44.png

Видите под картинкой вылазит все описание и кнопки редактирования и удаления
как будто мы внутри топика

topic_footer - topic_header на главной
а в демо на ЛС только превью и все

**Comment by acobat** [comment]
?

**Comment by 5nook** [comment]
извините за долгий ответ, приболел, вы еще не разобрались с блоками? Могу скинуть настройку для конфига

и второй вопрос тоже актуален?

поправлю завтра

**Comment by acobat** [comment]
да, большое превью все равно не активно.
блоки поплыли - многие ссылки в меню и в меню юзера сбоку (где выпадает) ... не работают. по ссылкам - www.site.com/#

**Comment by 5nook** [comment]
у вас есть пример в виде сайта? чтобы посмотреть так сказать проблемы на теле

**Comment by acobat** [comment]
да, сайт под разработкой, и запаролен. 
вы бы не могли мне в скайп стукнуть? expertrussia

пожалуйста,

**Comment by 5nook** [comment]
извините через скайп не веду обслуживание

буду пробовать решить ваши задачи

**Comment by 5nook** [comment]
второй пункт поправили, закачайте себе новый файл виджета с репозитория из ветки алто

**Comment by 5nook** [comment]
первую ошибку не удалось реализовать попробовал все варианты, но у меня подозрения что вы не правильно настроили свой конфиг 

закрываю таск, если более подробно опишите ситуацию, или предоставите ссылки, откройте заново, с удовольствием решим вашу беду

**Comment by 5nook** [comment]
вспомнил что у вас алто, но ошибки в данной версии шаблона нету, возможно ошибка была в старой версии шаблона, попробуйте переустановить шаблон
