### ISSUE TITLE
Две иконки «замок» на закрытых блогах

### ISSUE THREAD

**Issue by ekoum** [CheDESIGNER/prestige#42]
Рядом с названием закрытого блога присутстсуют сразу две иконки замка, при том разные. Как оставить только черную?
Примеры тут: http://ekoum.ru/blogs/
И тут http://ekoum.ru/blog/shop/

**Comment by 5nook** [comment]
хороший баг нашли :) молодцы

поправлен.

но не черный замок, а белый извините

**Comment by 5nook** [comment]
вот рабочий пример
http://prestige.lstemplates.com/blogs/
http://prestige.lstemplates.com/blog/travel/
http://prestige.lstemplates.com/blog/travel/38.html
