### ISSUE TITLE
Обновление шаблона

### ISSUE THREAD

**Issue by SimWhite** [CheDESIGNER/prestige#44]
Подскажите, можно ли как-то вынести изменения в отдельные файлы? Как конфигурация LS настраивается в файле .local, по тому же принципу, чтобы при обновлении темы, не затирались изменения. Либо, как вариант, при обновлении явно указывать какие файлы были изменены, чтобы не обновлять весь шаблон, а заменить только требуемые.

**Comment by CheDESIGNER** [comment]
Мы думаем над этим, как выясним как лучше это реализовать, сообщим.

**Comment by CheDESIGNER** [comment]
"Либо, как вариант, при обновлении явно указывать какие файлы были изменены, чтобы не обновлять весь шаблон, а заменить только требуемые."
Так в гите все это предусмотрено, вы можете видеть когда и где редактировались файлы, если перейдете в папку "prestige" на гите https://github.com/Chedesigner/prestige/tree/livestreet/templates/skin/prestige

**Comment by 5nook** [comment]
да все верно написано, для этого и есть гит, и вы можете зайти в коммиты и посмотреть какие файлы были справлено, с учетом временного интервала, все просто
