### ISSUE TITLE
Шаблон под DAO компании

### ISSUE THREAD

**Issue by acobat** [CheDESIGNER/prestige#46]
Привет!
Вы не подскажите будет ли оптимизация под плагин DAO компании от екстраверта, и примерные сроки пожалуйста? Нам это очень важно :)

**Comment by acobat** [comment]
Сроков нет, а, друзья?

**Comment by 5nook** [comment]
Извините за долгий ответ. К сожалению пока что нету. Занимаемся адаптацией плагина Компании, после чего скорей всего займемся ДАО.

**Comment by acobat** [comment]
Привет! Спасибо за ответ! Можно ли как то ускорить верстку в течении например ближайших двух недель закончить ДАО Компании, за, скажем, донейт?

**Comment by 5nook** [comment]
Да именно такими мотивациями я думаю и ускоряется процесс верстки плагинов :) либо параллельный заказ.

Но насчет двух недель, я вам честно скажу что сомневаюсь. Все таки вам надо обсудить это с @Chedesigner. Напишите ему на почту например раз он тут не отвечает. Но я его попрошу заглянуть в этот таск, так как он решает на счет направлений по разработке.
