### ISSUE TITLE
Плагин «OpenComments»

### ISSUE THREAD

**Issue by wilsden** [CheDESIGNER/prestige#48]
Прошу адаптировать этот плагин

**Comment by CheDESIGNER** [comment]
Занес в список.

**Comment by NickGodspeed** [comment]
там не сложно подлечить самому. смотрите blogmoto.com.ua - пару минут делов. Если нужно будет по свободе сравню с исходниками и покажу что закоментить (в шаблоне самого опен комент, он врядли будет обновляться, потому можно править смело)
