### ISSUE TITLE
Подписка на комментарии (галочка отсутствует)

### ISSUE THREAD

**Issue by CheDESIGNER** [CheDESIGNER/prestige#50]
http://livestreet.ru/uploads/images/01/41/83/2013/10/31/9f9b9b44ca.jpg

**Comment by 5nook** [comment]
Так было в дизайне
http://dl.dropbox.com/u/78791311/2013.11.02-18.57.06.jpg

Если надо могу поправить

но это связано с задачей #24 

что выбираем как делаем?

вызываю @Chedesigner

**Comment by CheDESIGNER** [comment]
Если юзер подписался, надо что бы надпись заменялась на "отписаться".

**Comment by 5nook** [comment]
то есть галочку не делаем как я понял, ок

**Comment by CheDESIGNER** [comment]
Да, можно и без нее обойтись
