### ISSUE TITLE
новости не выводятся в виде masonry

### ISSUE THREAD

**Issue by riente** [CheDESIGNER/prestige#55]
поставил новую altocms, поставил шаблон под нее, плагины, конфиги прописал, как сказано, но новости не выводятся в виде masonry, а имеют следующий вид
![screen](https://cloud.githubusercontent.com/assets/4803190/3007115/afffd91e-de6c-11e3-8b2c-951eb4c26d83.jpg)

может я что-то упустил? подскажите, пожалуйста, где может быть проблема

**Comment by riente** [comment]
сделал все по новой, и теперь работает, сам не знаю, где накосячил, извините за беспокойство

**Comment by CheDESIGNER** [comment]
Ничего страшного, обращайтесь если что :)
