### ISSUE TITLE
Кнопка создать видна для гостей

### ISSUE THREAD

**Issue by wilsden** [CheDESIGNER/prestige#6]
Гости и не авторизованные пользователи видят кнопку создать. в конфиге было отключено сжатие js и css файлов 

![bandicam 2013-08-31 21-22-37-359](https://f.cloud.github.com/assets/5324536/1062671/ba3aa994-1262-11e3-8715-fe42e70f3989.jpg)

**Comment by 5nook** [comment]
хотел бы задать вопросу @Chedesigner это у нас правда баг или фитча? :)

**Comment by CheDESIGNER** [comment]
Это не баг, просто если пользователь не авторизован при клике на "создать" должна всплывать форма авторизации.

**Comment by 5nook** [comment]
а у нас формы не появляется, сделать?

**Comment by CheDESIGNER** [comment]
Нет, у нас показывается страница 404. Да, сделай пожалуйста.

**Comment by wilsden** [comment]
Решили эту проблему или нет?

**Comment by 5nook** [comment]
сегодня решим ждите

**Comment by 5nook** [comment]
задача решена
