### ISSUE TITLE
Превью видео в мобильной версии

### ISSUE THREAD

**Issue by YaroslavWise** [CheDESIGNER/prestige#7]
В мобильной версии видео не масштабируется в экран
![screenshot_2013-09-05-14-08-15](https://f.cloud.github.com/assets/5371758/1087263/80211126-1613-11e3-8a06-50375200aa3d.png)

**Comment by 5nook** [comment]
спасибо поправим сегодня как раз к обновлению

**Comment by 5nook** [comment]
решено

**Comment by wilsden** [comment]
№ 7 я не нашел((

**Comment by 5nook** [comment]
пример в этом топике
http://prestige.lstemplates.com/blog/cars/9.html

а вот как бы смотрелось на телефоне
http://quirktools.com/screenfly/#u=http%3A//prestige.lstemplates.com/blog/cars/9.html&w=320&h=568&a=37&s=1
