### ISSUE TITLE
Вопросы по скрытию элементов и размещению GA

### ISSUE THREAD

**Issue by YaroslavWise** [CheDESIGNER/prestige#9]
1. Пока не работает авторизация через соц. сети, этот блок хотелось бы скрыть. В каком файле это можно сделать? И в продолжение: когда заработает? :)
2. В какой файл можно вставить скрипт GA?

**Comment by 5nook** [comment]
1.
prestige\window_login.tpl
строки 30-34
это будет реализовано через плагин. Когда не могу сказать пока что.
2.
в любой :) но как говорит гугль надо вставлять в самый низ, а это footer.tpl

**Comment by YaroslavWise** [comment]
В том то и дело, что при попытке вставить в этот tpl, падает весь сайт.

**Comment by 5nook** [comment]
скорей всего вы не используете заветные тэги {literal}....код....{/literal}, которые так заботливо были придуманы для вас :) много миллионов лет назад. И не раз обсуждены :)))

**Comment by Killallpeople** [comment]
> это будет реализовано через плагин. Когда не могу сказать пока что.
> хотелось бы на будущее, при реализации плагина добавьте возможность обязательного запроса имейла при регистрации через соц сети.
